---
- name: Check Disk Space
  hosts: all
  gather_facts: yes

  tasks:
    - name: Display disk space
      shell: df -h
      register: disk_space_output

    - name: Print disk space information
      debug:
        msg: "{{ disk_space_output.stdout_lines }}"
